apiVersion: v1
kind: PersistentVolume
metadata:
 name: elastic-data-pv
 labels:
   type: local
spec:
 # we will be using the default dynamic storage provisoner   storageClassName: manual
 capacity:
   storage: 100Mi
 accessModes:
   - ReadWriteOnce
 hostPath:
   path: "users/macbook/kubedata/todo/elastic"